<?xml version="1.0" encoding="utf-8"?><Database Name="Escuela" Class="SQLConnectionDBEscuelaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ESTRADA\SQLEXPRESS;Initial Catalog=Escuela;Integrated Security=True" SettingsObjectName="ConsultasLINQ.Properties.Settings" SettingsPropertyName="EscuelaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Estudiantes" Member="Estudiantes">
    <Type Name="Estudiante">
      <Column Name="AlumnoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Carrera" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dirección" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>